version: '3.12.5'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
